import {
  SiJavascript,
  SiFastify,
  SiPhp,
  SiTypescript,
  SiGo,
  SiLua,
  SiWordpress,
  SiCplusplus,
  SiGnubash,
  SiReact,
  SiPreact,
  SiNodedotjs,
  SiPrisma,
  SiSvelte,
  SiExpress,
  SiNestjs,
  SiPython,
  SiWebpack,
  SiVite,
  SiTailwindcss,
  SiChakraui,
  SiMui,
  SiUnocss,
  SiMongodb,
  SiPostgresql,
  SiMysql,
  SiRedis,
  SiDocker,
  SiLinux,
  SiGit,
  SiPodman,
  SiSqlite,
  SiStyledcomponents,
  SiDaisyui,
  SiFirebase,
  SiArchlinux,
} from "react-icons/si"

import {
  TbBrandMantine,
  TbBrandNextjs,
  TbBrandRadixUi,
  TbBrandReactNative,
  TbBrandSolidjs,
} from "react-icons/tb"

export const Icon = {
  Javascript: SiJavascript,
  Typescript: SiTypescript,
  PHP: SiPhp,
  Go: SiGo,
  CPlusPlus: SiCplusplus,
  Python: SiPython,
  Bash: SiGnubash,
  Lua: SiLua,
  React: SiReact,
  ReactNative: TbBrandReactNative,
  Nextjs: TbBrandNextjs,
  Solid: TbBrandSolidjs,
  Svelte: SiSvelte,
  Preact: SiPreact,
  Webpack: SiWebpack,
  Vite: SiVite,
  Tailwind: SiTailwindcss,
  DaisyUI: SiDaisyui,
  Uno: SiUnocss,
  Radix: TbBrandRadixUi,
  StyledComponent: SiStyledcomponents,
  Chakra: SiChakraui,
  Mantine: TbBrandMantine,
  MUI: SiMui,
  Express: SiExpress,
  Fastify: SiFastify,
  Nestjs: SiNestjs,
  Prisma: SiPrisma,
  Nodejs: SiNodedotjs,
  WordPress: SiWordpress,
  Postgresql: SiPostgresql,
  MySQL: SiMysql,
  SQLite: SiSqlite,
  Mongo: SiMongodb,
  Redis: SiRedis,
  Firebase: SiFirebase,
  Git: SiGit,
  Docker: SiDocker,
  Podman: SiPodman,
  Linux: SiLinux,
  ArchLinux: SiArchlinux,
}
